{% set name = "pytest-selenium" %}
{% set version = "4.1.0" %}
{% set hash = "b0a4e1f27750cde631c513c87ae4863dcf9e180e5a1d680a66077da8a669156c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/{{ name }}/pytest_selenium-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - hatch-vcs >=0.3
    - hatchling >=1.13
  run:
    - python
    - pytest >=6.0.0
    - pytest-base-url >=2.0.0
    - pytest-html >=4.0.0
    - pytest-variables >=2.0.0
    - selenium >=4.10.0
    - requests >=2.26.0
    - tenacity >=6.0.0
  run_constrained:
    - appium-python-client >=1.0.0

test:
  imports:
    - pytest_selenium
    - pytest_selenium.drivers

about:
  home: https://pypi.org/pypi/pytest-selenium
  license: MPL 2.0
  license_file: LICENSE
  summary: pytest-selenium is a plugin for py.test that provides support for running Selenium based tests.

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus