travis:
  secure:
    BINSTAR_TOKEN: g3Qa0Ry5Dwi/I9DSwG9+SX/sg3yDKxquEpDI/A86H4ZwxYV7pACgswlRGEsOmpIS1ezlPWtXE8paExpG6ZD4zjTY9CgDtO2Vx1XTmmx2Yplis8H3kpi7/3ltAJI63J3lvJ7V0vjSqvNNg0b84ae5Gmjvy475cnckhvCVimIMhLTuD+0uqIsgNblkaXvld5zNv+ydqUuOsljgKPSmaha08YpQF8GXmo/cA6GF8QQDSlu89Qd+0LiFwD4o6nZPp5vilJC9wp/R/qIGIMXNgfam4eShN9ssGetUuZ/5gosEnBlj0YEXBP0ja9bTqa9YfUtEPbGQp0OmIp7NuR1Qv+jxFAl3RIm2oxZKWikIODzX0W/3IBS/pfhOHwvVJe09m1L72kIJrq009+XzZfQd49+Xq8HB/3XTUXDcTJcI4qiP2usFCYf2y643UF+AjiOiF8x5aObkrKkkHBxnN7JC9gtPPTAlL1MQ4LVOiH/Bgk/xFxL8gUTu09T31XDe53Gf7xcGt5SrbmDftKFS2L9QKPamS/rCyDO8oPafWq8GDEzPw1FMZ+o9PwpJPkG6zVV3GDfUKJEiHWVzl7XRIePotFXeNGkJKp0YopdQmYBSYngJxuQWWGK+I/sCPL8zXMZ9GSl1OOy0E55gwGl2qe39raPkL464zGP3Mq/Vna0lhXFOoo0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
