travis:
  secure:
    BINSTAR_TOKEN: fzK/01FuHtG8KqLkNxjCayH0gxqFkDHNnEFAy9oo2dqklH+40EYVe5AT3+c91nG+hKBMKXZJLoM9WhDjtW9VdLI9Q1NU+WRI0aXpNpk6fTJDi3U9LhVTbdXisH0UG21m5DFgDqdO1bj/Q9JwL0X7W2pQXwsaGtefgKflJkDww3dMTmADaeK5t9qihvwPb7hO6Ya6wXIRDFN8822guVuS7+t2IXfLuBPrPS4PV05zF8NnsaEjVL0PW289I5G4py23gEvUAgTIehAQMHnSof3T/dXyFJYbZc8QwR7f9sbZveX/zpAhrgsIzr7pIJh9mWmytfFn2hhHUvRd191N22CVzJQOqYGKMZniVHuOL75B2xsoX8U3Oty40cbyLj+Op4kPw4ek6vkPX/tqb6oEnSDMVnz8R3Y+X2NyuIfz1Z5KXbqpDUyM4O3HEXIRd9pfvB8p970NljYzSysc1FHBdE3+6VnQC5j6bgFCwfDiW+Xov9NfDCSRfohNSNVBRSv2cWmeQNRwfT7SmZasEl9pehJYjz24anJuVNamTBHaDXWLUwKl+jw15VGzF01+S8fk0M8rRnj+jUPB205TUbyOEGX18/l8D/wf9XAJeqtj27EQVB3ismiOyq6JE2A9wyrYjcBC1SZFC7x3Um11Or27Kzlebxs5m+gAMGHpn7B5f7pLaBE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
