travis:
  secure:
    BINSTAR_TOKEN: hbf6mtZS8cBMhAywaKRRWdGj0tX6/14YO99uc3RJdWcKOWdjquPU4osij3GdWiZErj5bLzKRYXgYmCHp0W7PPzZp2PYnnY3jYmjFN5hRHtPXOZgXsgWd19HCDzF5eyqoWeEMUTG9BFWBmmjhKdD6PZfpHl5QZ+ybPApzjV0CRVidGyH8RPuEZ80EqgNFcip1bIzrcMKHKuvGyXp8KPOlUTkl2nAm+ZtbBnpgBQyS0ZIJ0TZi9/vGjDemDq+5zkoArvOu4R7MrR8He9dL3H/DTSbKPW4ohneCY/zL8fg/xp/El3bxpe9H3a1aap0dxQ6z5tzy/DEz7X4VPCkE88bir5PJDHhQO7HBziLV0b6uib6nbQTv+/voOpQvLXCbtDa3oFpNTx1d+B27x2XRm4c9mHAP54mjVk94UhpePu6i87Gr66KG6XQ1jvU1+bC6k4RtM3QJ+b6gFbl9JJ3nnzRjyYv1811ofmcEXFYAZUgJrMfhDFocaoIIkMFpcbA0T9kTbgeOxlyjc/kffkiF1m93vYPhQgtHbuFHVMJV2XEPAtzOqusWwciAVvEKxIjF8MWGhO8oMRbqh9+4WPIJyeWMAMqljBkxoNbZpiJObCagja2+X2rJVzRGIPFEfOpp29YIUdao+MmfyGbkN5u37k5PYIiuf6WhYPjR9FHzGEDoL8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
