travis:
  secure:
    BINSTAR_TOKEN: d6prQ2hDLQPTt8h3RteflBms1YAs21+Wsv9WSpCH/HMwSpXTp7mxz9X0LGVr5NudbGvIN07D1kzgbyTwyym7CgliUlnEffQqcoS0EoaTn50B5slGzxpWWUsFllJLA8BcZb2hSPgI1WPF4IXg3ZZXed5hqOeGtMthoEunECRoYaR3yGmGdhVjvR5szl3m7FtsFZNC5mgMbSDB1SR6ByHeWI+zs+S+h8p+05orhg9lIhHzd4whhTQ6yeXnjTbyjcbRjSKAwLuPEjcSY3guTuRUFWTeiXWcRs586q4cX7qP7rQawmMFXud/94q/auAeKuBJkfMB3ANh2bxpyTKAzMTLa3BFh64F/VQihBwgWXZMHJILfAoOzPWlKHmT1JjeQwBuEJIBxQPV5hZP1j0+qoeoBRSPT9FL455k4Qs/8rPypYxC1X5Y3KgHt/EeVNEtkNYzWRR0qkZvpc9aYJwx9dd2zTWHA44Kesiw4FInS2p4oVuV3/PGsLXcdhLBZuswx39uNsV1n+OPfaDpYpX2NJ3VhKX/GoW6OLG3L4hKvg7ZGMp88QP2x/xnrfdnxyGOkNZRvR6Uh2h228dU+Ag1lrk7/NmfpHkiwDjVcpIY1wlALdT/AxOLdqC/ZN1bPo/KwnHhxVWeqAjY2/ChX4F/q7Nh0JRvMUEPLh39SqkobeZnh4E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
